# Network
rnn_type: GRU #RNN, LSTM, GRU, SRU
bidirectional: false
embedding_size: 100
hidden_size: 100
num_layers: 4
dropout: 0.0
atten_model: dot #general, dot, none
# Decode
decode_max_length: 100
beam_size: 1

# Vocab
share_embedding: false
# Set vocab limit size
src_vocab_size: 30000
tgt_vocab_size: 30000


# File
train_src_file: /home/xiapeng/gaojun/data/trans/train.cn
train_tgt_file: /home/xiapeng/gaojun/data/trans/train.en

dev_src_file: /home/xiapeng/gaojun/trans/test/nist02.cn
dev_tgt_file: /home/xiapeng/gaojun/trans/test/nist02.en0

src_vocab_file: /home/xiapeng/gaojun/JunNMT_test/nmt_test/src_vocab.cn
tgt_vocab_file: /home/xiapeng/gaojun/JunNMT_test/nmt_test/tgt_vocab.en

# Misc
USE_CUDA: true

# Train
optim_method: adadelta #adadelta, adam, sgd
max_grad_norm: 5
learning_rate: 0.0004
num_train_epochs: 100
steps_per_stats: 100
steps_per_eval: 1000
batch_size: 20
out_dir: 