# Network
encoder_type:
decoder_type: InputFeedDecoder #InputFeedDecoder, AttnDecoder, ScheduledDecoder
rnn_type: LSTM #RNN, LSTM, GRU
bidirectional: true
embedding_size: 500
hidden_size: 500
num_layers: 2
dropout: 0.3
atten_model: general #general, dot, none

src_max_len: 50
tgt_max_len: 50

src_vocab_size: 30000
tgt_vocab_size: 30000

test_bleu: true

multi_bleu_src: /home/gaojun4ever/Documents/Projects/mt-exp/data/dev/nist02.cn
multi_bleu_refs: # Multiple reference
  - /home/gaojun4ever/Documents/Projects/mt-exp/data/dev/nist02.en0
  - /home/gaojun4ever/Documents/Projects/mt-exp/data/dev/nist02.en1
  - /home/gaojun4ever/Documents/Projects/mt-exp/data/dev/nist02.en2
  - /home/gaojun4ever/Documents/Projects/mt-exp/data/dev/nist02.en3


# Misc
use_cuda: true
random_seed: 3435

# Train
optim_method: sgd #adadelta, adam, sgd
max_grad_norm: 5
learning_rate: 1
learning_rate_decay: 0.9
start_decay_at: 8
weight_decay: 0.000001 #  weight decay(L2 penalty)
num_train_epochs: 100
steps_per_stats: 100
steps_per_eval: 1000
train_batch_size: 64
train_shard_size: 32
start_epoch_at: 

valid_batch_size: 32



# Test
decode_max_length: 100
beam_size: 3

out_dir: ./out_dir # path to save model
log_dir: ./log_dir # for tensorboard logdir