# Network
rnn_type: GRU #LSTM, GRU, SRU
bidirectional: true
embedding_size: 100
hidden_size: 100
num_layers: 2
dropout: 0.1
atten_model: dot
decode_max_length: 100
# Vocab
share_embedding: false
# Set vocab limit size(not support yet)
# src_vocab_size: 30000
# tgt_vocab_size: 30000


# File
train_src_file: /home/xiapeng/python/process_data/res/train_src_file
train_tgt_file: /home/xiapeng/python/process_data/res/train_tgt_file
# train_src_file: /home/xiapeng/python/process_data/res/deve_src_file
# train_tgt_file: /home/xiapeng/python/process_data/res/deve_tgt_file
dev_src_file: /home/xiapeng/python/process_data/res/deve_src_file
dev_tgt_file: /home/xiapeng/python/process_data/res/deve_tgt_file
src_vocab_file: /home/xiapeng/python/process_data/res/vocab.txt
tgt_vocab_file: /home/xiapeng/python/process_data/res/vocab.txt
# Misc
USE_CUDA: true

# Train
learning_rate: 0.0001
num_train_epochs: 100
steps_per_stats: 100
steps_per_eval: 1000
batch_size: 20
out_dir: ../sru_test0